name: Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'
          cache-dependency-path: '**/zensical.toml'

      - name: Zensical build cache
        uses: actions/cache@v4
        with:
          path: .cache
          key: ${{ runner.os }}-zensical-${{ hashFiles('**/zensical.toml', '**/mkdocs.yml') }}
          restore-keys: |
            ${{ runner.os }}-zensical-

      - run: |
          pip install zensical
          pip install mkdocs-material

      - run: zensical build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - id: deployment
        uses: actions/deploy-pages@v4
